### ISSUE TITLE
Show/Hide Details panel

### ISSUE THREAD

**Issue by c-sanchez** [phempshall/http-headers#15]
Can be nice to have option to Show/Hide the Request/Response window
Check these example images
![hide panel image](https://i.ibb.co/2cnXR88/hidepanel.png)
![show panel image](https://i.ibb.co/CBDJQ9p/showpanel.png)

**Comment by phempshall** [comment]
Duplicate of [https://github.com/phempshall/http-headers/issues/16](https://github.com/phempshall/http-headers/issues/16)
